### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by vinnykalisa**
[DEMO LINK](https://vinnykalisa.github.io/react_static-list-of-todos/)

### CODE REVIEW

File: src/components/TodoInfo/TodoInfo.tsx [hunk 1]
```diff
@@ -1,4 +1,21 @@
...
+
+export const TodoInfo: React.FC<TodoProps> = ({ todo }) => (
+  <article
+    className={classNames('TodoInfo', {
+      'TodoInfo--completed': todo.completed,
+    })}
+  >
+    <h2 className="TodoInfo__title">{todo.title}</h2>
+    {todo.user
+      && <UserInfo user={todo.user} />}
```
Comment (jstmpelowycz) [inline src/components/TodoInfo/TodoInfo.tsx:19]:
```suggestion
    <h2 className="TodoInfo__title">
      {title}
    </h2>

    {user && (
      <UserInfo user={user} />
    )}
```

File: src/components/TodoInfo/TodoInfo.tsx [hunk 2]
```diff
@@ -1,4 +1,21 @@
-// Add the required types and props
-export const TodoInfo = () => (
-  <>TodoInfo markup</>
+import React from 'react';
+import classNames from 'classnames';
+
+import { Todo } from '../../types/Todo';
+import { UserInfo } from '../UserInfo';
+
+type TodoProps = {
```
Comment (jstmpelowycz) [inline src/components/TodoInfo/TodoInfo.tsx:7]: just `Props`, keep it simple

File: src/components/UserInfo/UserInfo.tsx [hunk 3]
```diff
@@ -1,4 +1,13 @@
-// Add the required types and props
-export const UserInfo = () => (
-  <>UserInfo markup</>
+import React from 'react';
+
+import { User } from '../../types/User';
+
+type UserInfoProps = {
```
Comment (jstmpelowycz) [inline src/components/UserInfo/UserInfo.tsx:5]: > just `Props`, keep it simple

File: src/components/TodoList/TodoList.tsx [hunk 4]
```diff
@@ -1,4 +1,16 @@
-// Add the required types and props
-export const TodoList = () => (
-  <>TodoList markup</>
+import React from 'react';
+
+import { Todo } from '../../types/Todo';
+import { TodoInfo } from '../TodoInfo';
+
+type TodoProps = {
```
Comment (jstmpelowycz) [inline src/components/TodoList/TodoList.tsx:6]: > just `Props`, keep it simple

**Review by jstmpelowycz — CHANGES_REQUESTED** [review]

File: src/components/TodoInfo/TodoInfo.tsx [hunk 5]
```diff
@@ -1,4 +1,32 @@
...
+
+export const TodoInfo: React.FC<Props> = ({
+  todo: {
+    title,
+    completed,
+    user,
+  },
+}) => (
+
+  <article
```
Comment (SerhiiKirik) [inline src/components/TodoInfo/TodoInfo.tsx:19]: It's hard to read
```suggestion
  todo }) => (
  const {
    title,
    completed,
    user,
  } = todo;

  <article
```

File: src/components/TodoInfo/TodoInfo.tsx [hunk 6]
```diff
@@ -1,4 +1,32 @@
...
+      'TodoInfo--completed': completed,
+    })}
+  >
+    <h2 className="TodoInfo__title">
+      {title}
+    </h2>
+
+    {user && (
+      <UserInfo user={user} />
+    )}
```
Comment (SerhiiKirik) [inline src/components/TodoInfo/TodoInfo.tsx:30]:
```suggestion
    {user && <UserInfo user={user} />}
```

File: src/components/TodoInfo/TodoInfo.tsx (hunk 5 above)
Comment (vinnykalisa) [reply src/components/TodoInfo/TodoInfo.tsx:19]: > It's hard to read

why it says Cannot find name 'todo' then?

Comment (SerhiiKirik) [reply src/components/TodoInfo/TodoInfo.tsx]: Bc if you will have 3-4 props & you make 2 times destructuring what would be?
It's a bad practice

**Review by SerhiiKirik — APPROVED** [review]
Sync 🕺
